from django.core.management.base import BaseCommand
from tdee_calculator.models import Meal

class Command(BaseCommand):
    help = 'Thêm dữ liệu mẫu cho mô hình Meal'

    def handle(self, *args, **options):
        meals = [
            # Dữ liệu mẫu về món ăn
            {'name': 'Bông cải xanh', 'calories': 34, 'protein': 2.8, 'carbs': 6.6, 'fats': 0.4, 'fiber': 2.6, 'sugar': 1.7, 'sodium': 33, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Canxi, Sắt'},
            {'name': 'Cà rốt', 'calories': 41, 'protein': 0.9, 'carbs': 9.6, 'fats': 0.2, 'fiber': 2.8, 'sugar': 4.7, 'sodium': 69, 'meal_type': 'vegetable', 'vitamins': 'A, K', 'minerals': 'Kali, Canxi'},
            {'name': 'Ức gà', 'calories': 165, 'protein': 31, 'carbs': 0, 'fats': 3.6, 'fiber': 0, 'sugar': 0, 'sodium': 74, 'meal_type': 'white_meat', 'vitamins': 'B3, B6', 'minerals': 'Phosphorus, Selenium'},
            {'name': 'Cá hồi', 'calories': 206, 'protein': 22, 'carbs': 0, 'fats': 13.0, 'fiber': 0, 'sugar': 0, 'sodium': 59, 'meal_type': 'fish', 'vitamins': 'B12, D', 'minerals': 'Selenium, Phosphorus'},
            {'name': 'Quinoa', 'calories': 120, 'protein': 4.1, 'carbs': 21.3, 'fats': 1.9, 'fiber': 2.8, 'sugar': 0.9, 'sodium': 5, 'meal_type': 'grain', 'vitamins': 'B1, B2', 'minerals': 'Magnesium, Sắt'},
            {'name': 'Gạo lứt', 'calories': 111, 'protein': 2.6, 'carbs': 23.0, 'fats': 0.9, 'fiber': 1.8, 'sugar': 0.4, 'sodium': 5, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Magnesium, Phosphorus'},
            {'name': 'Sữa chua Hy Lạp', 'calories': 59, 'protein': 10, 'carbs': 3.6, 'fats': 0.4, 'fiber': 0, 'sugar': 4.0, 'sodium': 36, 'meal_type': 'dairy', 'vitamins': 'B12, B2', 'minerals': 'Canxi, Phosphorus'},
            {'name': 'Hạnh nhân', 'calories': 576, 'protein': 21.2, 'carbs': 21.6, 'fats': 49.9, 'fiber': 12.5, 'sugar': 4.4, 'sodium': 1, 'meal_type': 'snack', 'vitamins': 'E', 'minerals': 'Magnesium, Canxi'},
            {'name': 'Táo', 'calories': 52, 'protein': 0.3, 'carbs': 14.0, 'fats': 0.2, 'fiber': 2.4, 'sugar': 10.4, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C', 'minerals': 'Kali'},
            {'name': 'Socola đen', 'calories': 546, 'protein': 4.9, 'carbs': 61.0, 'fats': 31.0, 'fiber': 7.0, 'sugar': 24.0, 'sodium': 24, 'meal_type': 'dessert', 'vitamins': 'E', 'minerals': 'Magnesium, Sắt'},
            {'name': 'Mì Ý', 'calories': 131, 'protein': 5.0, 'carbs': 25.0, 'fats': 1.1, 'fiber': 1.3, 'sugar': 0.6, 'sodium': 1, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Sắt'},
            {'name': 'Sò', 'calories': 148, 'protein': 22.0, 'carbs': 4.0, 'fats': 4.0, 'fiber': 0, 'sugar': 0, 'sodium': 51, 'meal_type': 'fish', 'vitamins': 'B12', 'minerals': 'Kẽm, Sắt'},
            {'name': 'Bánh mì', 'calories': 265, 'protein': 9.0, 'carbs': 49.0, 'fats': 3.2, 'fiber': 2.7, 'sugar': 5.0, 'sodium': 491, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Sắt, Magie'},
            {'name': 'Thịt bò', 'calories': 250, 'protein': 26.0, 'carbs': 0.0, 'fats': 17.0, 'fiber': 0, 'sugar': 0, 'sodium': 55, 'meal_type': 'red_meat', 'vitamins': 'B12, B6', 'minerals': 'Sắt, Kẽm'},
            {'name': 'Đậu hũ', 'calories': 76, 'protein': 8.0, 'carbs': 2.0, 'fats': 4.0, 'fiber': 0.3, 'sugar': 0.3, 'sodium': 5, 'meal_type': 'vegetable', 'vitamins': 'B1, B2', 'minerals': 'Canxi, Sắt'},
            {'name': 'Bắp cải', 'calories': 25, 'protein': 1.3, 'carbs': 5.0, 'fats': 0.1, 'fiber': 2.5, 'sugar': 3.2, 'sodium': 18, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Canxi, Kali'},
            {'name': 'Chuối', 'calories': 89, 'protein': 1.1, 'carbs': 23.0, 'fats': 0.3, 'fiber': 2.6, 'sugar': 12.2, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, B6', 'minerals': 'Magnesium, Kali'},
            {'name': 'Khoai tây', 'calories': 77, 'protein': 2.0, 'carbs': 17.6, 'fats': 0.1, 'fiber': 2.2, 'sugar': 0.8, 'sodium': 6, 'meal_type': 'vegetable', 'vitamins': 'C, B6', 'minerals': 'Kali, Phosphorus'},
            {'name': 'Nho', 'calories': 69, 'protein': 0.7, 'carbs': 18.0, 'fats': 0.2, 'fiber': 0.9, 'sugar': 15.5, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, K', 'minerals': 'Kali'},
            {'name': 'Thịt gà', 'calories': 239, 'protein': 27.0, 'carbs': 0.0, 'fats': 14.0, 'fiber': 0, 'sugar': 0, 'sodium': 82, 'meal_type': 'white_meat', 'vitamins': 'B3, B6', 'minerals': 'Phosphorus, Selenium'},
            {'name': 'Tôm', 'calories': 99, 'protein': 24.0, 'carbs': 0.0, 'fats': 1.0, 'fiber': 0, 'sugar': 0, 'sodium': 150, 'meal_type': 'fish', 'vitamins': 'B12, B3', 'minerals': 'I-ốt, Kẽm'},
            {'name': 'Súp lơ', 'calories': 34, 'protein': 2.8, 'carbs': 6.6, 'fats': 0.4, 'fiber': 2.6, 'sugar': 1.7, 'sodium': 33, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Canxi, Sắt'},
            {'name': 'Cà chua', 'calories': 18, 'protein': 0.9, 'carbs': 3.9, 'fats': 0.2, 'fiber': 1.2, 'sugar': 2.6, 'sodium': 5, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Kali, Magie'},
            {'name': 'Tôm', 'calories': 99, 'protein': 24, 'carbs': 0.2, 'fats': 0.3, 'fiber': 0, 'sugar': 0, 'sodium': 150, 'meal_type': 'seafood', 'vitamins': 'B12, D', 'minerals': 'Kẽm, Selen'},
            {'name': 'Hạt chia', 'calories': 486, 'protein': 16.5, 'carbs': 42.1, 'fats': 30.7, 'fiber': 34.4, 'sugar': 0.0, 'sodium': 16, 'meal_type': 'grain', 'vitamins': 'B1, B2', 'minerals': 'Canxi, Magie'},
            {'name': 'Khoai tây', 'calories': 77, 'protein': 2.0, 'carbs': 17.6, 'fats': 0.1, 'fiber': 2.2, 'sugar': 0.8, 'sodium': 6, 'meal_type': 'vegetable', 'vitamins': 'C, B6', 'minerals': 'Kali, Sắt'},
            {'name': 'Sữa tươi', 'calories': 61, 'protein': 3.2, 'carbs': 4.8, 'fats': 3.3, 'fiber': 0, 'sugar': 5.0, 'sodium': 46, 'meal_type': 'dairy', 'vitamins': 'B12, D', 'minerals': 'Canxi, Phốt pho'},
            {'name': 'Bánh mì', 'calories': 265, 'protein': 9.0, 'carbs': 49.0, 'fats': 3.2, 'fiber': 2.7, 'sugar': 5.0, 'sodium': 491, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Sắt, Magie'},
            {'name': 'Mì ống', 'calories': 157, 'protein': 5.8, 'carbs': 30.9, 'fats': 0.9, 'fiber': 1.5, 'sugar': 0.6, 'sodium': 1, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Sắt, Canxi'},
            {'name': 'Yến mạch', 'calories': 389, 'protein': 16.9, 'carbs': 66.3, 'fats': 6.9, 'fiber': 10.6, 'sugar': 0.4, 'sodium': 2, 'meal_type': 'grain', 'vitamins': 'B1, B5', 'minerals': 'Magie, Sắt'},
            {'name': 'Măng tây', 'calories': 20, 'protein': 2.2, 'carbs': 3.7, 'fats': 0.2, 'fiber': 2.1, 'sugar': 1.2, 'sodium': 1, 'meal_type': 'vegetable', 'vitamins': 'K, A', 'minerals': 'Sắt, Canxi'},
            {'name': 'Hạnh nhân', 'calories': 576, 'protein': 21.2, 'carbs': 21.6, 'fats': 49.9, 'fiber': 12.5, 'sugar': 4.4, 'sodium': 1, 'meal_type': 'snack', 'vitamins': 'E, B2', 'minerals': 'Magie, Canxi'},
            {'name': 'Dưa hấu', 'calories': 30, 'protein': 0.6, 'carbs': 7.6, 'fats': 0.2, 'fiber': 0.4, 'sugar': 6.2, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, A', 'minerals': 'Kali, Magie'},
            {'name': 'Mít', 'calories': 95, 'protein': 2.4, 'carbs': 23.8, 'fats': 0.6, 'fiber': 1.5, 'sugar': 19.1, 'sodium': 2, 'meal_type': 'fruit', 'vitamins': 'C, B6', 'minerals': 'Magie, Canxi'},
            {'name': 'Đậu nành', 'calories': 446, 'protein': 36.5, 'carbs': 30.2, 'fats': 19.9, 'fiber': 9.3, 'sugar': 7.3, 'sodium': 15, 'meal_type': 'vegetable', 'vitamins': 'K, B9', 'minerals': 'Sắt, Canxi'},
            {'name': 'Mứt dừa', 'calories': 330, 'protein': 0.3, 'carbs': 88.0, 'fats': 0.4, 'fiber': 6.0, 'sugar': 69.0, 'sodium': 15, 'meal_type': 'dessert', 'vitamins': 'E, B6', 'minerals': 'Magie, Canxi'},
            {'name': 'Bánh quy', 'calories': 460, 'protein': 6.0, 'carbs': 65.0, 'fats': 20.0, 'fiber': 2.0, 'sugar': 17.0, 'sodium': 300, 'meal_type': 'snack', 'vitamins': 'B1, B2', 'minerals': 'Sắt, Canxi'},
            {'name': 'Trà xanh', 'calories': 1, 'protein': 0.0, 'carbs': 0.0, 'fats': 0.0, 'fiber': 0.0, 'sugar': 0.0, 'sodium': 1, 'meal_type': 'beverage', 'vitamins': 'C, E', 'minerals': 'Mangan, Magie'},
            {'name': 'Nho', 'calories': 69, 'protein': 0.6, 'carbs': 18.1, 'fats': 0.2, 'fiber': 0.9, 'sugar': 15.5, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, K', 'minerals': 'Kali, Đồng'},
            {'name': 'Cá hồi', 'calories': 206, 'protein': 22.1, 'carbs': 0, 'fats': 13.2, 'fiber': 0, 'sugar': 0, 'sodium': 50, 'meal_type': 'fish', 'vitamins': 'B12, D', 'minerals': 'Selen, Omega-3'},
            {'name': 'Quả bơ', 'calories': 160, 'protein': 2.0, 'carbs': 8.5, 'fats': 14.7, 'fiber': 6.7, 'sugar': 0.7, 'sodium': 7, 'meal_type': 'fruit', 'vitamins': 'K, E', 'minerals': 'Kali, Magie'},
            {'name': 'Sò điệp', 'calories': 84, 'protein': 18.2, 'carbs': 2.4, 'fats': 0.8, 'fiber': 0, 'sugar': 0, 'sodium': 55, 'meal_type': 'seafood', 'vitamins': 'B12, D', 'minerals': 'Selen, Kali'},
            {'name': 'Bí ngòi', 'calories': 17, 'protein': 1.2, 'carbs': 3.1, 'fats': 0.3, 'fiber': 1.0, 'sugar': 2.5, 'sodium': 8, 'meal_type': 'vegetable', 'vitamins': 'C, A', 'minerals': 'Magie, Mangan'},
            {'name': 'Trứng gà', 'calories': 155, 'protein': 12.6, 'carbs': 1.1, 'fats': 10.6, 'fiber': 0, 'sugar': 1.1, 'sodium': 126, 'meal_type': 'dairy', 'vitamins': 'B12, D', 'minerals': 'Sắt, Canxi'},
            {'name': 'Cà rốt', 'calories': 41, 'protein': 0.9, 'carbs': 9.6, 'fats': 0.2, 'fiber': 2.8, 'sugar': 4.7, 'sodium': 69, 'meal_type': 'vegetable', 'vitamins': 'A, K', 'minerals': 'Kali, Sắt'},
            {'name': 'Thịt gà', 'calories': 239, 'protein': 27.3, 'carbs': 0, 'fats': 14.0, 'fiber': 0, 'sugar': 0, 'sodium': 82, 'meal_type': 'white_meat', 'vitamins': 'B3, B6', 'minerals': 'Phốt pho, Selen'},
            {'name': 'Gạo lứt', 'calories': 111, 'protein': 2.6, 'carbs': 23.0, 'fats': 0.9, 'fiber': 1.8, 'sugar': 0.2, 'sodium': 1, 'meal_type': 'grain', 'vitamins': 'B1, B3', 'minerals': 'Magie, Sắt'},
            {'name': 'Khoai lang', 'calories': 86, 'protein': 1.6, 'carbs': 20.1, 'fats': 0.1, 'fiber': 3.0, 'sugar': 4.2, 'sodium': 55, 'meal_type': 'vegetable', 'vitamins': 'A, C', 'minerals': 'Kali, Mangan'},
            {'name': 'Sầu riêng', 'calories': 147, 'protein': 1.5, 'carbs': 33.1, 'fats': 5.3, 'fiber': 3.8, 'sugar': 13.7, 'sodium': 5, 'meal_type': 'fruit', 'vitamins': 'C, B6', 'minerals': 'Kali, Đồng'},
            {'name': 'Rau diếp', 'calories': 15, 'protein': 1.4, 'carbs': 2.9, 'fats': 0.2, 'fiber': 1.0, 'sugar': 0.5, 'sodium': 28, 'meal_type': 'vegetable', 'vitamins': 'A, K', 'minerals': 'Canxi, Sắt'},
            {'name': 'Dầu ô liu', 'calories': 884, 'protein': 0, 'carbs': 0, 'fats': 100, 'fiber': 0, 'sugar': 0, 'sodium': 0, 'meal_type': 'beverage', 'vitamins': 'E, K', 'minerals': 'Kali, Canxi'},
            {'name': 'Cá ngừ', 'calories': 132, 'protein': 28.0, 'carbs': 0, 'fats': 1.0, 'fiber': 0, 'sugar': 0, 'sodium': 50, 'meal_type': 'fish', 'vitamins': 'B12, D', 'minerals': 'Kẽm, Selen'},
            {'name': 'Nấm', 'calories': 22, 'protein': 3.1, 'carbs': 3.3, 'fats': 0.3, 'fiber': 1.0, 'sugar': 0.6, 'sodium': 5, 'meal_type': 'vegetable', 'vitamins': 'D, B2', 'minerals': 'Selen, Đồng'},
            {'name': 'Hạt điều', 'calories': 553, 'protein': 18.2, 'carbs': 30.2, 'fats': 43.9, 'fiber': 3.3, 'sugar': 5.2, 'sodium': 12, 'meal_type': 'snack', 'vitamins': 'E, K', 'minerals': 'Kali, Magie'},
            {'name': 'Bông cải trắng', 'calories': 25, 'protein': 2.0, 'carbs': 4.0, 'fats': 0.1, 'fiber': 2.1, 'sugar': 1.7, 'sodium': 30, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Canxi, Sắt'},
            {'name': 'Bưởi', 'calories': 42, 'protein': 0.8, 'carbs': 10.7, 'fats': 0.1, 'fiber': 1.4, 'sugar': 8.5, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, A', 'minerals': 'Kali, Magie'},
            {'name': 'Bánh xèo', 'calories': 230, 'protein': 9.0, 'carbs': 30.0, 'fats': 10.0, 'fiber': 2.0, 'sugar': 0.5, 'sodium': 300, 'meal_type': 'main', 'vitamins': 'B1, B3', 'minerals': 'Sắt, Canxi'},
            {'name': 'Rau diếp', 'calories': 15, 'protein': 1.4, 'carbs': 2.9, 'fats': 0.2, 'fiber': 1.3, 'sugar': 0.4, 'sodium': 5, 'meal_type': 'vegetable', 'vitamins': 'A, K', 'minerals': 'Canxi, Kali'},
            {'name': 'Măng', 'calories': 27, 'protein': 2.6, 'carbs': 5.4, 'fats': 0.1, 'fiber': 2.6, 'sugar': 0.6, 'sodium': 6, 'meal_type': 'vegetable', 'vitamins': 'A, C', 'minerals': 'Sắt, Magie'},
            {'name': 'Quả lê', 'calories': 57, 'protein': 0.4, 'carbs': 15.2, 'fats': 0.1, 'fiber': 3.1, 'sugar': 9.8, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C, K', 'minerals': 'Kali, Đồng'},
            {'name': 'Sò huyết', 'calories': 90, 'protein': 16.6, 'carbs': 2.0, 'fats': 2.0, 'fiber': 0, 'sugar': 0, 'sodium': 75, 'meal_type': 'seafood', 'vitamins': 'B12, D', 'minerals': 'Selen, Kẽm'},
            {'name': 'Bắp ngô', 'calories': 96, 'protein': 3.4, 'carbs': 21.0, 'fats': 1.5, 'fiber': 2.4, 'sugar': 6.3, 'sodium': 15, 'meal_type': 'vegetable', 'vitamins': 'B1, B3', 'minerals': 'Magie, Phosphorus'},
            {'name': 'Hạt dẻ', 'calories': 213, 'protein': 2.0, 'carbs': 44.0, 'fats': 2.2, 'fiber': 7.0, 'sugar': 0.8, 'sodium': 1, 'meal_type': 'nut', 'vitamins': 'B6, E', 'minerals': 'Magie, Canxi'},
            {'name': 'Nấm', 'calories': 22, 'protein': 3.1, 'carbs': 3.3, 'fats': 0.3, 'fiber': 1.0, 'sugar': 0.6, 'sodium': 5, 'meal_type': 'vegetable', 'vitamins': 'D, B2', 'minerals': 'Kali, Selen'},
            {'name': 'Rau ngót', 'calories': 23, 'protein': 2.0, 'carbs': 4.0, 'fats': 0.3, 'fiber': 2.0, 'sugar': 0.7, 'sodium': 6, 'meal_type': 'vegetable', 'vitamins': 'A, C', 'minerals': 'Sắt, Canxi'},
            {'name': 'Mứt táo', 'calories': 275, 'protein': 0.3, 'carbs': 70.0, 'fats': 0.1, 'fiber': 1.2, 'sugar': 61.0, 'sodium': 5, 'meal_type': 'dessert', 'vitamins': 'C', 'minerals': 'Kali, Magie'},
            {'name': 'Thịt heo', 'calories': 242, 'protein': 25.0, 'carbs': 0.0, 'fats': 16.0, 'fiber': 0, 'sugar': 0, 'sodium': 60, 'meal_type': 'red_meat', 'vitamins': 'B12, B6', 'minerals': 'Sắt, Kẽm'},
            {'name': 'Rau mồng tơi', 'calories': 22, 'protein': 2.3, 'carbs': 4.0, 'fats': 0.3, 'fiber': 2.0, 'sugar': 0.5, 'sodium': 8, 'meal_type': 'vegetable', 'vitamins': 'A, C', 'minerals': 'Sắt, Canxi'},
            {'name': 'Bắp cải tím', 'calories': 31, 'protein': 1.3, 'carbs': 6.3, 'fats': 0.2, 'fiber': 2.1, 'sugar': 3.2, 'sodium': 18, 'meal_type': 'vegetable', 'vitamins': 'C, K', 'minerals': 'Kali, Canxi'},
            {'name': 'Bánh crepe', 'calories': 145, 'protein': 4.5, 'carbs': 24.5, 'fats': 3.5, 'fiber': 0.5, 'sugar': 1.5, 'sodium': 322, 'meal_type': 'dessert', 'vitamins': 'B1, B2', 'minerals': 'Sắt, Canxi'},
            {'name': 'Hải sản nướng', 'calories': 156, 'protein': 23.0, 'carbs': 0.3, 'fats': 6.0, 'fiber': 0, 'sugar': 0, 'sodium': 80, 'meal_type': 'seafood', 'vitamins': 'B12, D', 'minerals': 'Kẽm, Selen'},
            {'name': 'Nước cam', 'calories': 45, 'protein': 0.7, 'carbs': 10.3, 'fats': 0.2, 'fiber': 0.2, 'sugar': 8.4, 'sodium': 1, 'meal_type': 'beverage', 'vitamins': 'C, A', 'minerals': 'Kali, Magie'},
            {'name': 'Đậu phộng', 'calories': 567, 'protein': 25.8, 'carbs': 16.1, 'fats': 49.2, 'fiber': 8.4, 'sugar': 4.7, 'sodium': 18, 'meal_type': 'nut', 'vitamins': 'E, B1', 'minerals': 'Magie, Đồng'},
            {'name': 'Chanh', 'calories': 29, 'protein': 1.1, 'carbs': 9.3, 'fats': 0.3, 'fiber': 2.8, 'sugar': 2.5, 'sodium': 1, 'meal_type': 'fruit', 'vitamins': 'C', 'minerals': 'Kali, Magie'},
            {'name': 'Cà phê', 'calories': 2, 'protein': 0.3, 'carbs': 0, 'fats': 0, 'fiber': 0, 'sugar': 0, 'sodium': 5, 'meal_type': 'beverage', 'vitamins': 'B2', 'minerals': 'Mangan, Kali'},
        ]

        for meal in meals:
            Meal.objects.create(**meal)
        
        self.stdout.write(self.style.SUCCESS('Đã thêm dữ liệu mẫu cho mô hình Meal!'))
