# Generated by Django 5.1.1 on 2024-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdee_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(help_text='Fats in grams'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(help_text='Protein in grams'),
        ),
    ]
