# Generated by Django 5.1.1 on 2024-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdee_calculator', '0002_alter_meal_carbs_alter_meal_fats_alter_meal_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
    ]
