# Generated by Django 5.1.1 on 2024-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdee_calculator', '0003_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('snack', 'Snack'), ('main', 'Main Meal'), ('red_meat', 'Red Meat'), ('white_meat', 'White Meat'), ('fish', 'Fish'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('fruit', 'Fruit'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='snack', max_length=20),
        ),
    ]
